### ISSUE TITLE
Icon for Chrome (notes) is low resolution

### ISSUE THREAD

**Issue by Colopatiron** [JasonLG1979/gnome-shell-extension-mpris-indicator-button#24] opened 2019-12-03 01:41 UTC
The icons for lollypop and other players are nice, but the default notes one that shows up when something's playing on Chrome is very low resolution.

![image](https://user-images.githubusercontent.com/1519903/70012927-ec3bf080-15b0-11ea-80c9-ac7a2937c63e.png)

That is on a 1080p screen. Maybe replace that icon with something else -- maybe even browser-specific?

I'm using the latest version of the extension.

**Comment by JasonLG1979** [comment] 2019-12-04 02:52
What icon and shell theme are you using? 

The cover icon's size is dynamically determined by the height of the track info. So for example if it's 32px high then the icon size is set to 32px. It may not always be the exact size as the icon theme provides but generally that's OK because svg (vector) icons scale pretty well and the shell will try to use the closest size. It however looks like shit if you scale png (raster) icons. To me that looks like maybe theme you're using does not provide a svg version of that icon. If that's the case then I would suggest filing a bug report with the maker of the icon theme. If that's not the case and they do ship a svg icon we can look further into it.

**Comment by JasonLG1979** [comment] 2019-12-04 02:58
Almost forgot, the icon's name is ```audio-x-generic-symbolic```

**Comment by Colopatiron** [comment] 2019-12-04 11:49
I'm using `Matcha-dark-azul` shell theme and the `la-capitaine` icon set.
Can you recommend good icon sets that work with this extension?

**Comment by JasonLG1979** [comment] 2019-12-06 03:29
I can confirm the issue with that particular icon.

I checked in [the repo of that icon set](https://github.com/keeferrourke/la-capitaine-icon-theme) And they do provide a svg for that icon. But for some reason GNOME shell just does not like it at all. This is the 1st time I've ever seen a symbolic svg icon that does not scale well. I'm not sure what's going on? The strange thing is that in GNOME's image viewer it scales up just fine. Maybe it's something in the svg file itself, again I don't know.

All I do know is this is not my bug. Whatever this issue is either the icon or something in GNOME Shell It's got nothing to do with me. I would file a bug report against the icon theme.

**Closed** 2019-12-06 03:30 UTC
Labels: not our bug
