### ISSUE TITLE
Lollypop - Secondary Click to "Raise/Minimize Toggle" also toggles Lollypop window minimise/maximise 

### ISSUE THREAD

**Issue by djsing** [JasonLG1979/gnome-shell-extension-mpris-indicator-button#31] opened 2020-03-20 10:58 UTC
**Steps to reproduce**

**Case 1:**
Lollypop window is maximised.
-> Secondary click on the mpris-indicator-button
_Expected result:_ mpris indicator maximises to show current song etc.
_Actual result:_ mpris indicator maximises to show current song etc. as well as minimises Lollypop window.
-> Secondary click on the mpris-indicator-button
_Expected result:_ mpris indicator minimises
_Actual result:_ mpris indicator minimises as well as maximises Lollypop window.

**Case 1:**
Lollypop window is minimised.
-> Secondary click on the mpris-indicator-button
_Expected result:_ mpris indicator maximises to show current song etc.
_Actual result:_ mpris indicator maximises to show current song etc. as well as maximises Lollypop window.
-> Secondary click on the mpris-indicator-button
_Expected result:_ mpris indicator minimises
_Actual result:_ mpris indicator minimises as well as minimises Lollypop window.

-----------------------------------------------------------------------------------------------------------

Nothing too major, other than this the functionality of the indicator is really good.

**Comment by fdinardo** [comment] 2020-03-20 11:20
Yes I can confirm, this happen with Spotify as well.
Actually, I tested with Rhythmbox, and it's the same, so I am assuming that this affects all the applications.

Basically the secondary click on the icon trigger the Maximize/minimize toggle.

other info:
Gnome-shell version: 3.36
Distro: Arch-Linux
Mpris-indicator version: latest from gnome-extensions.

I have noticed another weird style when hovering the icon. But It's better to open another issue for that.

**Comment by JasonLG1979** [comment] 2020-03-20 14:12
> Basically the secondary click on the icon trigger the Maximize/minimize toggle.

Secondary clicks on the indicator icon toggles minimize/raise. That's the intended behavior.

**Comment by JasonLG1979** [comment] 2020-03-20 14:18
As per @fdinardo this should be fixed with the latest git master and will be pushed with the rest of the 3.36 fixes once they are complete.

**Closed by JasonLG1979** 2020-03-20 14:18 UTC

**Comment by djsing** [comment] 2020-03-21 19:55
Thanks so much!
