### ISSUE TITLE
Add Gnome Podcasts to display artwork?

### ISSUE THREAD

**Issue by Scotty-Trees** [JasonLG1979/gnome-shell-extension-mpris-indicator-button#44] opened 2020-10-04 22:09 UTC
Currently on Pop!_OS 20.04 fully updated, Gnome 3.36.3, using Gnome Podcasts flatpak v0.4.8 and the MPRIS extension does show the Podcast icon in the top panel (as well as any other icon that is currently being used; vivaldi, rhythmbox, etc), which I think is great (works for my Tauon music box player flatpak app as well), but when I click the extension Gnome Podcasts doesn't display the artwork for the currently playing podcast, it just shows the Gnome Podcast application icon. Now I understand (or rather maybe assume) that Pop!_OS is a mixture of Gnome versions or something like that, so this may not even be able to be fixed for me, but if it is even possible, I will still give it a try to at least ask you since it can't hurt after all. Below is a screenshot just to illustrate what I'm seeing. 

![Screenshot from 2020-10-04 17-04-16](https://user-images.githubusercontent.com/45135187/95028218-4d66a180-0664-11eb-9d01-c473b333509a.png)

**Comment by JasonLG1979** [comment] 2020-10-05 00:27
If you don't see cover art it's because none is provided or it's running into the same bug as Spotify.  https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button/issues/15

**Comment by JasonLG1979** [comment] 2020-10-05 02:50
It seems to work fine for me on Ubuntu 20.04.
![Screenshot from 2020-10-04 21-49-27](https://user-images.githubusercontent.com/6667703/95035751-a1d14780-068b-11eb-852d-f55992f6d6f9.png)

**Comment by Scotty-Trees** [comment] 2020-10-05 03:21
You know, it's honestly probably something related to Pop!_OS I bet, but I'm not wise enough to know exactly where to go track that down. I do have one quick attempt though if you'll humor me, do you have the flatpak app Flatseal installed? It allows you to set some permissions for flatpaks. I honestly highly doubt that would fix this issue, but on the slight chance maybe it could, here's what my flatseal settings look like for Podcasts, maybe yours are similar, or different, but I'd be willing to test any differences to see. Feel free to correct me if I'm wrong haha. Btw thanks for taking the time to checking this issue out. 
![Screenshot from 2020-10-04 22-17-42](https://user-images.githubusercontent.com/45135187/95037209-d3e4a880-068f-11eb-96c5-540613f7ecbc.png)
![Screenshot from 2020-10-04 22-17-56](https://user-images.githubusercontent.com/45135187/95037212-d7782f80-068f-11eb-99e9-733b0059455e.png)
![Screenshot from 2020-10-04 22-18-06](https://user-images.githubusercontent.com/45135187/95037216-dc3ce380-068f-11eb-9a40-56d6f70b0fc1.png)

**Comment by JasonLG1979** [comment] 2020-10-05 03:44
My flatpak permissions are the same. I haven't changed them for any app. I don't even use GNOME Podcasts, I just installed it to test against this bug. I also didn't have flatseal installed either again I just installed it to compare with your permissions.

 [d-feet](https://flathub.org/apps/details/org.gnome.dfeet) and [Logs](https://flathub.org/apps/details/org.gnome.Logs) are the easiest way to debug mpris/dbus issues.

Check the logs for errors by searching for ```@JasonLG1979.github.io``` if there is an error loading cover art it will be logged. We'll start with that.

**Comment by JasonLG1979** [comment] 2020-10-05 03:55
You can also look and see what GNOME Podcast is giving mpris for cover art with dbus. Look for ```mpris:artUrl``` in the metadata. You can check to see if it's a valid url by opening it in a browser.
![Screenshot from 2020-10-04 22-50-42](https://user-images.githubusercontent.com/6667703/95038792-a9491e80-0694-11eb-8ec8-ca0e1e2c08c4.png)

**Comment by Scotty-Trees** [comment] 2020-10-05 03:57
Checking out Gnome Logs, under the All tab, when I go to play a Podcast episode, Logs does show this error at the top of the list, hope it's somewhat relevant: The sender is gnome-shell 

```
JS ERROR: Extension mprisindicatorbutton@JasonLG1979.github.io: Gio.IOErrorEnum: Operation not supported
getCover/<@/home/scott/.local/share/gnome-shell/extensions/mprisindicatorbutton@JasonLG1979.github.io/widgets.js:70:50
```
Screenshot below for full detail:
![Screenshot from 2020-10-04 22-55-10](https://user-images.githubusercontent.com/45135187/95038857-c67ded00-0694-11eb-88e8-d8af25ad0ea8.png)

Give me a moment and I'll check out D-feet, haven't eve used it before but just installed it.

**Comment by JasonLG1979** [comment] 2020-10-05 03:58
> Give me a moment and I'll check out D-feet, haven't eve used it before but just installed it.

It looks like #15 to me.

**Comment by JasonLG1979** [comment] 2020-10-05 04:00
#15 basically means that extensions can not load remote images.

**Comment by Scotty-Trees** [comment] 2020-10-05 04:01
My D-feet entry looks a bit empty compared to yours! If the screenshot is a bit hard to see, I can go into dark mode.

![Screenshot from 2020-10-04 23-00-05](https://user-images.githubusercontent.com/45135187/95039089-73586a00-0695-11eb-862f-ffcb27bc1d59.png)

**Comment by JasonLG1979** [comment] 2020-10-05 04:03
Podcast has to actually be playing something.

**Comment by Scotty-Trees** [comment] 2020-10-05 04:06
Yup, Podcasts is actually playing something right now

![Screenshot from 2020-10-04 23-05-36](https://user-images.githubusercontent.com/45135187/95039375-2c1ea900-0696-11eb-897c-1ecb5eeec045.png)

**Comment by JasonLG1979** [comment] 2020-10-05 04:08
Double click the metadata field.

**Comment by JasonLG1979** [comment] 2020-10-05 04:11
This appears to be a duplicate of #15 to me. I'd file a bug report with pop. THe upstream bug is here: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2284

**Comment by JasonLG1979** [comment] 2020-10-05 04:13
I'm going to close this as a duplicate. There's nothing I can do to fix the issue it's an upstream bug.

**Closed by JasonLG1979** 2020-10-05 04:13 UTC

**Comment by Scotty-Trees** [comment] 2020-10-05 04:14
Okay no worries, thanks for taking the time to look into it. I'll follow up with Pop and upstream for now. And thanks again for making a sweet extension.

**Comment by JasonLG1979** [comment] 2020-10-05 04:20
Thank you, I'm glad someone finds it useful. Sorry I couldn't help you fully resolve the issue. Believe me I say that I wish the GNOME people weren't continually break things. It's like they don't test things...
