### ISSUE TITLE
Add position slider for players that support it correctly

### ISSUE THREAD

**Issue by webmastak** [JasonLG1979/gnome-shell-extension-mpris-indicator-button#18] opened 2019-10-29 13:08 UTC
Show position slider for players that support it correctly. 
For example **Rhythmbox** and other analogues.
It would be nice. 😉

**Comment by JasonLG1979** [comment] 2019-10-29 14:53
Duplicate of https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button/issues/11

**Closed by JasonLG1979** 2019-10-29 14:53 UTC
