### ISSUE TITLE
It would be nice to add a position slider for local players.

### ISSUE THREAD

**Issue by Mishlem** [JasonLG1979/gnome-shell-extension-mpris-indicator-button#20] opened 2019-10-30 20:44 UTC
You can add a position slider and display for local players who do not shout in the stream?

**Comment by JasonLG1979** [comment] 2019-10-30 20:52
Duplicate of https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button/issues/11

**Closed by JasonLG1979** 2019-10-30 20:52 UTC

**Comment by Mishlem** [comment] 2019-10-30 22:25
Oops sorry.

**Comment by JasonLG1979** [comment] 2019-10-31 04:49
> I would like to fork for myself, but I am not good at Java Script, could you give a sketch of a code template so that I can start from something, thanks.

There is no way to give you a "code template" The JavaScript itself is not the complex part. It's the interplay of several different MPRIS properties that makes it complex. You would 1st need to understand the MPRIS spec very well. Me showing you how to do it would basically be me doing it and I'm not willing to put in that work for a feature I'm not going to use. You're talking about 1000+ lines of code easy. If you want to fork it and go on your own then well, you're on your own. I'm sorry.

**Comment by JasonLG1979** [comment] 2019-10-31 05:09
The relevant MPRIS bits are:

 https://specifications.freedesktop.org/mpris-spec/2.2/Player_Interface.html#Property:Position
 https://specifications.freedesktop.org/mpris-spec/2.2/Player_Interface.html#Property:CanSeek
https://specifications.freedesktop.org/mpris-spec/2.2/Player_Interface.html#Method:Seek
https://specifications.freedesktop.org/mpris-spec/2.2/Player_Interface.html#Method:SetPosition
https://specifications.freedesktop.org/mpris-spec/2.2/Player_Interface.html#Property:Rate
https://specifications.freedesktop.org/mpris-spec/2.2/Player_Interface.html#Simple-Type:Playback_Rate
https://specifications.freedesktop.org/mpris-spec/2.2/Player_Interface.html#Simple-Type:Time_In_Us
https://specifications.freedesktop.org/mpris-spec/2.2/Player_Interface.html#Property:Metadata
https://specifications.freedesktop.org/mpris-spec/2.2/Player_Interface.html#Signal:Seeked

That will give you an idea of the complexity and how easy it is for it to break with so many moving parts involved.

**Comment by Mishlem** [comment] 2019-10-31 12:08
>  You're talking about 1000+ lines of code easy.

Thanks for the answer, I did not think that this function is so difficult to implement.

**Comment by JasonLG1979** [comment] 2019-10-31 12:36
> Thanks for the answer, I did not think that this function is so difficult to implement.

That's why I decided not to do it. It's crazy hard to get right even if the player does what it's supposed to and most player's don't. so you end up doing all that work for a feature that's going to end up being broken most of the time anyway. It's not worth it.
